import PDFDocument from 'pdfkit'
import type { Organization } from '@/types/platform'

/**
 * Server-side PDF rendering with pdfkit. Every document shares the same
 * branded frame: forest header band, document number and date, agency
 * contact footer with page numbers. Templates only draw the body.
 */

export const COLORS = { forest: '#073423', gold: '#c28d38', ink: '#16211b', muted: '#5d6b63', line: '#e8e3d5', canvas: '#f7f4ec' }

export interface PdfFrame {
  organization: Organization
  title: string
  subtitle?: string
  number: string
  generatedAt?: Date
}

export type Doc = PDFKit.PDFDocument

const MARGIN = 48
const HEADER_H = 84

export function renderPdf(frame: PdfFrame, body: (doc: Doc, frame: PdfFrame) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margins: { top: HEADER_H + 28, bottom: 64, left: MARGIN, right: MARGIN }, bufferPages: true, info: { Title: frame.title, Author: frame.organization.name, Creator: 'Super Agent' } })
    const chunks: Buffer[] = []
    doc.on('data', (c: Buffer) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    try {
      body(doc, frame)
      finish(doc, frame)
      doc.end()
    } catch (error) {
      reject(error)
    }
  })
}

function drawHeader(doc: Doc, frame: PdfFrame) {
  const width = doc.page.width
  doc.save()
  doc.rect(0, 0, width, HEADER_H).fill(COLORS.forest)
  doc.rect(0, HEADER_H, width, 3).fill(COLORS.gold)
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(15).text(frame.organization.name, MARGIN, 24, { width: width - MARGIN * 2 - 200 })
  doc.fillColor(COLORS.gold).font('Helvetica-Bold').fontSize(8).text('SUPER AGENT', MARGIN, 46, { characterSpacing: 1.5 })
  if (frame.organization.licenceLabel) doc.fillColor('#ffffffaa').font('Helvetica').fontSize(8).text(frame.organization.licenceLabel, MARGIN, 58)
  doc.fillColor('#ffffff').font('Helvetica').fontSize(8.5)
  doc.text(frame.number, width - MARGIN - 200, 26, { width: 200, align: 'right' })
  doc.text(formatDate(frame.generatedAt ?? new Date()), width - MARGIN - 200, 40, { width: 200, align: 'right' })
  doc.restore()
}

function drawFooter(doc: Doc, frame: PdfFrame, page: number, total: number) {
  const width = doc.page.width
  const y = doc.page.height - 44
  doc.save()
  doc.moveTo(MARGIN, y - 10).lineTo(width - MARGIN, y - 10).lineWidth(0.5).strokeColor(COLORS.line).stroke()
  doc.fillColor(COLORS.muted).font('Helvetica').fontSize(7.5)
  const contact = [frame.organization.phone, frame.organization.email].filter(Boolean).join('  ·  ')
  doc.text(`${frame.organization.name}${contact ? `  ·  ${contact}` : ''}`, MARGIN, y, { width: width - MARGIN * 2 - 120 })
  doc.text(`Page ${page} of ${total}`, width - MARGIN - 120, y, { width: 120, align: 'right' })
  doc.text('Generated by Super Agent. This document summarises records held by the agency and is not a policy contract.', MARGIN, y + 11, { width: width - MARGIN * 2 })
  doc.restore()
}

function finish(doc: Doc, frame: PdfFrame) {
  const range = doc.bufferedPageRange()
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i)
    drawHeader(doc, frame)
    drawFooter(doc, frame, i - range.start + 1, range.count)
  }
}

/* ---------- Body helpers ---------- */

export function title(doc: Doc, text: string, subtitle?: string) {
  doc.fillColor(COLORS.forest).font('Helvetica-Bold').fontSize(20).text(text)
  if (subtitle) doc.moveDown(0.2).fillColor(COLORS.muted).font('Helvetica').fontSize(10.5).text(subtitle)
  doc.moveDown(0.8)
}

export function section(doc: Doc, text: string) {
  doc.moveDown(0.6)
  doc.fillColor(COLORS.gold).font('Helvetica-Bold').fontSize(8.5).text(text.toUpperCase(), { characterSpacing: 1.2 })
  const y = doc.y + 3
  doc.moveTo(MARGIN, y).lineTo(doc.page.width - MARGIN, y).lineWidth(0.5).strokeColor(COLORS.line).stroke()
  doc.moveDown(0.6)
}

export function paragraph(doc: Doc, text: string) {
  doc.fillColor(COLORS.ink).font('Helvetica').fontSize(10.5).text(text, { lineGap: 2 })
  doc.moveDown(0.4)
}

export function keyValues(doc: Doc, rows: [string, string][]) {
  const x = MARGIN
  const labelW = 150
  const valueW = doc.page.width - MARGIN * 2 - labelW
  for (const [label, value] of rows) {
    const y = doc.y
    doc.fillColor(COLORS.muted).font('Helvetica').fontSize(9.5).text(label, x, y, { width: labelW })
    doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(10).text(value || '—', x + labelW, y, { width: valueW })
    doc.moveDown(0.35)
  }
  doc.moveDown(0.3)
}

export function table(doc: Doc, columns: { label: string; width: number; align?: 'left' | 'right' }[], rows: string[][]) {
  const x0 = MARGIN
  const rowH = 20
  const head = () => {
    const y = doc.y
    doc.rect(x0, y, doc.page.width - MARGIN * 2, rowH).fill(COLORS.canvas)
    let x = x0
    doc.fillColor(COLORS.muted).font('Helvetica-Bold').fontSize(8)
    for (const c of columns) {
      doc.text(c.label.toUpperCase(), x + 6, y + 6, { width: c.width - 12, align: c.align ?? 'left', characterSpacing: 0.8 })
      x += c.width
    }
    doc.y = y + rowH
  }
  head()
  doc.fillColor(COLORS.ink).font('Helvetica').fontSize(9.5)
  for (const r of rows) {
    if (doc.y + rowH > doc.page.height - 70) {
      doc.addPage()
      head()
      doc.fillColor(COLORS.ink).font('Helvetica').fontSize(9.5)
    }
    const y = doc.y
    let x = x0
    r.forEach((cell, i) => {
      const c = columns[i]
      doc.text(cell, x + 6, y + 6, { width: c.width - 12, align: c.align ?? 'left', lineBreak: false, ellipsis: true })
      x += c.width
    })
    doc.moveTo(x0, y + rowH).lineTo(doc.page.width - MARGIN, y + rowH).lineWidth(0.4).strokeColor(COLORS.line).stroke()
    doc.y = y + rowH
  }
  if (!rows.length) {
    doc.fillColor(COLORS.muted).font('Helvetica-Oblique').fontSize(9.5).text('Nothing recorded yet.', x0 + 6, doc.y + 6)
    doc.moveDown(1)
  }
  doc.moveDown(0.6)
}

export function callout(doc: Doc, text: string) {
  const x = MARGIN
  const w = doc.page.width - MARGIN * 2
  const y = doc.y
  const h = doc.heightOfString(text, { width: w - 28 }) + 20
  doc.rect(x, y, w, h).fill(COLORS.canvas)
  doc.rect(x, y, 3, h).fill(COLORS.gold)
  doc.fillColor(COLORS.ink).font('Helvetica').fontSize(10).text(text, x + 14, y + 10, { width: w - 28 })
  doc.y = y + h
  doc.moveDown(0.8)
}

export function formatDate(d: Date | string): string {
  const date = typeof d === 'string' ? new Date(d) : d
  return new Intl.DateTimeFormat('en-KE', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Africa/Nairobi' }).format(date)
}

export function kes(amount: number | null): string {
  if (amount == null) return '—'
  return `KES ${new Intl.NumberFormat('en-KE', { maximumFractionDigits: 0 }).format(Math.round(amount))}`
}
